collections:
  comments:
    output: true
  environment:
    output: true
  functions:
    output: true
  general:
    output: true
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "smell"
title: "Clean Code: Smells and Heuristics"